GET https://mach-4zyf.onrender.com/api/account/orders/b7e93e4f-7da1-4af6-970d-3306f9d4f4c1

###

GET https://mach-4zyf.onrender.com/api/users

###

POST https://mach-4zyf.onrender.com/api/users/register
content-type: application/json

{
    "username": "ggg",
    "password": "testing",
    "firstName": "geo",
    "lastName": "lastname"
}

###

POST https://mach-4zyf.onrender.com/api/users/login
content-type: application/json

{
    "username": "gg",
    "password": "testing"
}

###